export const exempleData = [
    {
        idEmployee: 0,
        firstName: "Paul",
        lastName: "Georges",
        dateOfBirth: "06/18/2000",
        startDate: "09/01/2022",
        department: "Engineering",
        street: "1 rue le maire",
        city: "Nantes",
        state: "Pays de la loire",
        zipCode: "44000"
    },
    {
        idEmployee: 1,
        firstName: "Armand",
        lastName: "Thierry",
        dateOfBirth: "02/09/1998",
        startDate: "10/21/2022",
        department: "Engineering",
        street: "2 rue le maire",
        city: "Paris",
        state: "Ile de France",
        zipCode: "75000"
    },
    {
        idEmployee: 2,
        firstName: "Tony",
        lastName: "Parker",
        dateOfBirth: "11/18/1987",
        startDate: "01/07/2022",
        department: "Engineering",
        street: "13 rue le maire",
        city: "Le Mans",
        state: "Pays de la loire",
        zipCode: "72000"
    },
    {
        idEmployee: 3,
        firstName: "Paul",
        lastName: "Georges",
        dateOfBirth: "06/18/2000",
        startDate: "09/01/2022",
        department: "Engineering",
        street: "1 rue le maire",
        city: "Nantes",
        state: "Pays de la loire",
        zipCode: "44000"
    },
    {
        idEmployee: 4,
        firstName: "Armand",
        lastName: "Thierry",
        dateOfBirth: "02/09/1998",
        startDate: "10/21/2022",
        department: "Engineering",
        street: "2 rue le maire",
        city: "Paris",
        state: "Ile de France",
        zipCode: "75000"
    },
    {
        idEmployee: 5,
        firstName: "Tony",
        lastName: "Parker",
        dateOfBirth: "11/18/1987",
        startDate: "01/07/2022",
        department: "Engineering",
        street: "13 rue le maire",
        city: "Le Mans",
        state: "Pays de la loire",
        zipCode: "72000"
    },
    {
        idEmployee: 6,
        firstName: "Paul",
        lastName: "Georges",
        dateOfBirth: "06/18/2000",
        startDate: "09/01/2022",
        department: "Engineering",
        street: "1 rue le maire",
        city: "Nantes",
        state: "Pays de la loire",
        zipCode: "44000"
    },
    {
        idEmployee: 7,
        firstName: "Armand",
        lastName: "Thierry",
        dateOfBirth: "02/09/1998",
        startDate: "10/21/2022",
        department: "Engineering",
        street: "2 rue le maire",
        city: "Paris",
        state: "Ile de France",
        zipCode: "75000"
    },
    {
        idEmployee: 8,
        firstName: "Tony",
        lastName: "Parker",
        dateOfBirth: "11/18/1987",
        startDate: "01/07/2022",
        department: "Engineering",
        street: "13 rue le maire",
        city: "Le Mans",
        state: "Pays de la loire",
        zipCode: "72000"
    },
    {
        idEmployee: 9,
        firstName: "Paul",
        lastName: "Georges",
        dateOfBirth: "06/18/2000",
        startDate: "09/01/2022",
        department: "Engineering",
        street: "1 rue le maire",
        city: "Nantes",
        state: "Pays de la loire",
        zipCode: "44000"
    },
    {
        idEmployee: 10,
        firstName: "Armand",
        lastName: "Thierry",
        dateOfBirth: "02/09/1998",
        startDate: "10/21/2022",
        department: "Engineering",
        street: "2 rue le maire",
        city: "Paris",
        state: "Ile de France",
        zipCode: "75000"
    },
    {
        idEmployee: 11,
        firstName: "Tony",
        lastName: "Parker",
        dateOfBirth: "11/18/1987",
        startDate: "01/07/2022",
        department: "Engineering",
        street: "13 rue le maire",
        city: "Le Mans",
        state: "Pays de la loire",
        zipCode: "72000"
    }
]

export const exempleLabels = [
    { text: "First Name", value: "firstName" },
    { text: "Last Name", value: "lastName" },
    { text: "Start Date", value: "startDate" },
    { text: "Department", value: "department" },
    { text: "Date of Birth", value: "dateOfBirth" },
    { text: "Street", value: "street" },
    { text: "City", value: "city" },
    { text: "State", value: "state" },
    { text: "Zip Code", value: "zipCode" },
];